# Site settings
title: Chanuwas/New
email: chanuwas.asw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a cognitive science PhD student with background in computer science and data science experience.  
  I work on social dynamics and emergence of inequality.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chasnew.github.io" # the base hostname & protocol for your site
twitter_username: chas_new
github_username:  chasnew

# Build settings
markdown: kramdown
